### ISSUE TITLE
Ability to use ExternalSecrets to pass in Token

### ISSUE THREAD

**Issue by jwhitcraft** [vantage-sh/helm-charts#38]
Currently there is no way to use an already defined secrets to read in the token.  This is considered best practice todo this.

It would be great if this chart would support an already existing secret.

Thanks

**Comment by macb** [comment]
The token's secret can be passed via setting the `agent.secret.name` Value on the helm chart. Would this meet the expectations?

The reference will be used in the application template but the secret itself will not be created and the Vantage token is not required to be supplied (but would be needed at runtime from the specified secret).
```
➜  vantage-kubernetes-agent git:(main) helm template -n vantage vka . --set agent.secret.name="secret-token" --set agent.clusterID="foo" | grep -A2 "secret"
                secretKeyRef:
                  name: secret-token
                  key: token
```
